name: Generate plots

on:
  push:
    paths:
      - '**/*.csv.gz'
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    name: Generate plots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          working-directory: './utils/visualize'
      - name: Run visualization tool
        run: |
          cd ./utils/visualize && bash generate-all.sh ../../profile_library
      - uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/master'
        with:
          message: 'chore: generate plots'
          pull: '--rebase --autostash'
