name: Update profile library

on:
  pull_request:
    paths:
      - '.github/scripts/profile_library/**'
  push:
    paths:
      - '**/model.json'
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    name: Update profile library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install -r ${{ github.workspace }}/.github/scripts/profile_library/requirements.txt
      - name: Pull again
        run: git pull || true
      - name: Update library.json, authors and translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 ${{ github.workspace }}/.github/scripts/profile_library/update-library.py
      - uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/master'
        with:
          add: 'profile_library'
          message: 'Update profile library'
      - name: Wait 5 seconds
        run: sleep 5
      - name: Purge cloudflare cache
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache \
            --header "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            --header 'Content-Type: application/json' \
            --data '{
          	"files": [
          		"https://api.powercalc.nl/library"
          	]
          }'
